### ISSUE TITLE
README

### ISSUE THREAD

**Issue by wickedbeernut** [sparkfun/Qwiic_Button_Py#1]
Please update the README file to indicate which SparkFun "buttons" Qwiic_Button_Py is compatible with.  I assume Qwiic_Button_Py is compatible with,

- SparkFun Qwiic Button Breakout (BOB-15931)
- SparkFun Qwiic Button - Red LED (BOB-15932)
- SparkFun Qwiic Button - Green LED (BOB-16842)

Is Qwiic_Button_Py also compatible with,

- Qwiic Switch (SPX-15586)
- Qwiic Arcade - Red (SPX-15591)
- Qwiic Arcade - Blue (SPX-15592)

**Comment by makin-stuff** [comment]
Hi @wickedbeernut. This python module is compatible with all the products you listed. I've also updated the README. Thanks!
