### ISSUE TITLE
AttributeError: module 'qwiic_button' has no attribute 'Qwiic_Button'

### ISSUE THREAD

**Issue by TaylorHokanson** [sparkfun/Qwiic_Button_Py#2]
Hello,

Thanks for making this library; it's exactly what I was looking for! I have a BOB-15932 (red Qwiic button) hooked up to a Raspberry Pi 2B via Qwiic hat. I've installed the library via `sudo pip install sparkfun-qwiic-button`. When I try to run the sample code at the bottom of [this page](https://github.com/sparkfun/Qwiic_Button_Py), I get the following error: `AttributeError: module 'qwiic_button' has no attribute 'Qwiic_Button'`. Thoughts?

**Comment by TaylorHokanson** [comment]
Interesting; example 2 does work correctly, suggesting that there is some error in example 1.

**Comment by makin-stuff** [comment]
Hi there @TaylorHokanson. Thanks for finding this issue with the code on the readme. I've just updated that code, it should work for you now. I've tested the other examples and they work too. I'll be closing this issue. Let me know if anything else comes up.
